security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        OC\UserBundle\Entity\User: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /platform

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }